<#
.SYNOPSIS
PS102-ATLAS-Create-Audit-Batches.ps1 - ATLAS v1.1
Generated: 19/08/2026
.DESCRIPTION
Scans platform\ps-scripts\atlas\batch-02 to batch-20.
Backs up old audit-batches. Generates 19 batch audit.txt files + ATLAS-Combined-Grouping-Doc.md
USAGE:.\PS102-ATLAS-Create-Audit-Batches.ps1 -BasePath "C:\Atlas\atlas-workspace"
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$BasePath
)

$ErrorActionPreference = "Stop"
$WorkspaceRoot = $BasePath
$ScriptsRoot = Join-Path $WorkspaceRoot "platform\ps-scripts\atlas"
$DocsRoot = Join-Path $WorkspaceRoot "docs"
$OutputDir = Join-Path $ScriptsRoot "audit-batches"
$ArchiveRoot = Join-Path $ScriptsRoot "audit-batches-archive"
$DocPath = Join-Path $DocsRoot "ATLAS-Combined-Grouping-Doc.md"

Write-Host "=== PS102-ATLAS v1.1: Creating Audit Batches ===" -ForegroundColor Cyan

#region 1. BACKUP EXISTING
$Timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$BackupDir = Join-Path $ArchiveRoot $Timestamp

if (Test-Path $OutputDir) {
    New-Item -ItemType Directory -Path $BackupDir -Force | Out-Null
    Get-ChildItem $OutputDir | Move-Item -Destination $BackupDir -Force
    Write-Host "Backed up old audit-batches to $BackupDir" -ForegroundColor Yellow
}
New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
#endregion

#region 2. SCAN AND BUILD AUDITS
$BatchFolders = Get-ChildItem $ScriptsRoot -Directory | Where-Object {$_.Name -like "batch-*-*"} | Sort-Object Name
$AllDocs = [System.Collections.ArrayList]@()
$mdTables = [System.Collections.ArrayList]@()

$themes = @(
    "Security + EventBus","K8s Platform","Core Banking API","Payments","ESB & Migration",
    "Data Lake + BI","Fraud & Risk","NBO & Segmentation","Compliance","CRM & Contact Center",
    "Lending","Treasury","Channels","Observability","Platform Core",
    "AI Services","IAM & Security","Integrations","Platform Extensions"
)

$batchNum = 2
foreach($folder in $BatchFolders) {
    $scripts = Get-ChildItem $folder.FullName -Filter "PS*.ps1" | Sort-Object Name
    if($scripts.Count -eq 0) { continue }

    # Create batch audit txt
    $batchFile = Join-Path $OutputDir ("BATCH-{0:D2}-{1}.txt" -f $batchNum, $folder.Name)
    $batchContent = @()
    $batchContent += "BATCH $batchNum : $($folder.Name) | Generated $(Get-Date)"
    $batchContent += "================================================================="

    foreach($s in $scripts) {
        $batchContent += "=== $($s.Name) ==="
        $batchContent += Get-Content $s.FullName -Raw
        $batchContent += "--- END $($s.Name) ---`n"
        $psNum = ($s.Name -match '(PS\d+)')? $Matches[1] : "PS??"
        $null = $AllDocs.Add([PSCustomObject]@{Batch=$batchNum; Id=$psNum; Name=$s.Name})
    }

    $batchContent | Out-File $batchFile -Encoding utf8
    Write-Host "Created: $($batchFile | Split-Path -Leaf)" -ForegroundColor Green

    # Build MD table row
    $themeIndex = $batchNum - 2
    $theme = if($themeIndex -lt $themes.Count){ $themes[$themeIndex] } else { "TBD" }
    $range = "$($scripts[0].BaseName) to $($scripts[-1].BaseName)"
    $mdTables.Add("| $batchNum | $($folder.Name) | $range | $theme |") | Out-Null
    $batchNum++
}
#endregion

#region 3. GENERATE MASTER DOC
$docContent = @"
# ATLAS R17 Master Script Documentation
Generated: $(Get-Date)
Total Scripts: $($AllDocs.Count)
Location: atlas-workspace\docs\ATLAS-Combined-Grouping-Doc.md

## FOLDER CONVENTION
`orchestration\` = Drivers: ATLAS-MASTER-RUN, PS98-ATLAS-BackupRestore, PS99-ATLAS-Validate-And-Cleanup, PS100-ATLAS-Report-Generator, PS102-ATLAS-Create-Audit-Batches
`platform\ps-scripts\atlas\batch-XX\` = Workers: PS207-PS320

## BATCH MAPPING
| Batch | Folder | Scripts | Theme |
| --- | --- | --- | --- |
$(($mdTables) -join "`n")

## ATLAS COMPLIANCE NOTES
1. **EventBus**: Kafka with tenant_id header propagation
2. **Multi-Tenancy**: RLS on all tables via tenant_id
3. **Security**: Keycloak + JWT per tenant

*Generated by PS102-ATLAS-Create-Audit-Batches.ps1 v1.1*
"@

$docContent | Out-File $DocPath -Encoding utf8
Write-Host "PS102-ATLAS Done: $DocPath" -ForegroundColor Green
Write-Host "Archive: $ArchiveRoot" -ForegroundColor DarkGray
#endregion