<#
.SYNOPSIS
PS100-Report-Generator-125.ps1 - PS25 Audit Report v3.0
#>

param(
    [string]$BasePath = "C:\Atlas\releases\R01\demo-bank",
    [string]$ReportFormat = "MD"
)

$ScriptsRoot = Join-Path $BasePath "atlas-workspace\platform\ps-scripts"
$ReportDir = Join-Path $BasePath "reports"
New-Item -ItemType Directory -Path $ReportDir -Force | Out-Null
$Timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$ReportPath = Join-Path $ReportDir "PS25-Release-Report-$Timestamp.md"

# 1. COLLECT ALL SCRIPTS
$allScripts = Get-ChildItem "$ScriptsRoot\batch-*" -Recurse -Filter "PS*.ps1"
$scriptCount = $allScripts.Count

# 2. DOCKER HEALTH
$dockerStatus = docker compose -f "$BasePath\docker-compose.yml" -f "$BasePath\docker-compose-dw.yml" -f "$BasePath\docker-compose-bi.yml" ps --format json 2>$null | ConvertFrom-Json

# 3. BUILD REPORT
$report = @()
$report += "# PS25 Release Report v1.0.0-prod"
$report += "**Generated:** $(Get-Date)"
$report += "**BasePath:** $BasePath"
$report += "**Total Scripts:** $scriptCount"
$report += ""

$report += "## 1. Execution Summary"
$report += "| Check | Status |"
$report += "| --- | --- |"
$report += "| Total Scripts Delivered | $scriptCount |"
$report += "| Batches | 20 |"
$report += "| Platform | Spring Boot + React + RN + ClickHouse |"
$report += ""

$report += "## 2. Docker Health Status"
$report += "| Service | State | Ports |"
$report += "| --- | --- | --- |"
$dockerStatus | ForEach-Object {
    $report += "| $($_.Name) | $($_.State) | $($_.Publishers[0].PublishedPort) |"
}
$report += ""

$report += "## 3. Script Manifest"
$report += "| File | Batch |"
$report += "| --- | --- |"
$allScripts | ForEach-Object {
    $batch = ($_.Directory.Name -split '-')[1]
    $report += "| $($_.Name) | $batch |"
}
$report += ""
$report += "---"
$report += "*Generated by PS-MASTER-RUN-125.ps1*"

Set-Content $ReportPath ($report -join "`n") -Encoding UTF8
Write-Host "Report Created: $ReportPath" -ForegroundColor Green