<#
.SYNOPSIS
PS100-ATLAS-Report-Generator.ps1 - ATLAS R17 Report Generator v1.0
Generated: 18/08/2026
USAGE:.\PS100-ATLAS-Report-Generator.ps1 -BasePath "C:\Atlas\releases\R01\demo-bank"
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$BasePath
)

$ErrorActionPreference = "Stop"
$WorkspaceRoot = Join-Path $BasePath "_work-desk\atlas-workspace"
$ScriptsRoot = Join-Path $WorkspaceRoot "platform\ps-scripts\atlas"
$DocsRoot = Join-Path $WorkspaceRoot "docs"
$Timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$ReportMD = Join-Path $DocsRoot "ATLAS-Execution-Report-$Timestamp.md"
$ReportHTML = Join-Path $DocsRoot "ATLAS-Execution-Report-$Timestamp.html"

if (!(Test-Path $DocsRoot)) { New-Item $DocsRoot -ItemType Directory -Force | Out-Null }

#region SCAN BATCHES
Write-Host "=== PS100-ATLAS v1.0: Generating ATLAS Report ===" -ForegroundColor Cyan

$batchFolders = Get-ChildItem $ScriptsRoot -Directory | Where-Object {$_.Name -like "batch-*-*"} | Sort-Object Name
$reportData = [System.Collections.ArrayList]@()

$batchNum = 1
foreach($folder in $batchFolders) {
    $scripts = Get-ChildItem $folder.FullName -Filter "PS*.ps1" | Sort-Object Name
    if($scripts.Count -eq 0) { continue }

    $null = $reportData.Add([PSCustomObject]@{
        Batch = $batchNum
        Folder = $folder.Name
        ScriptCount = $scripts.Count
        Scripts = ($scripts.Name -join ", ")
    })
    $batchNum++
}
#endregion

#region GENERATE REPORTS
# MD Report
$md = @"
# ATLAS R17 Execution Report
Generated: $(Get-Date)
BasePath: $BasePath
Total Batches: $($reportData.Count)
Total Scripts: $(($reportData | Measure-Object ScriptCount -Sum).Sum)

## Batch Summary
| Batch | Folder | # Scripts | Scripts |
| --- | --- | --- | --- |
$(($reportData | ForEach-Object { "| $($_.Batch) | $($_.Folder) | $($_.ScriptCount) | $($_.Scripts) |" }) -join "`n")

## Compliance Notes
1. **EventBus**: Kafka 3.7 with X-Tenant-ID headers
2. **DB**: Postgres 16 with RLS per tenant_id
3. **Backup**: PS98-ATLAS with robocopy excludes
4. **Validation**: PS99-ATLAS healthchecks
5. **Audit**: PS102-ATLAS generates combined docs

*Generated by PS100-ATLAS-Report-Generator.ps1 v1.0*
"@
$md | Out-File $ReportMD -Encoding utf8

# HTML Report
$html = $md -replace "`n", "<br>" -replace "\|", "</td><td>"
"<html><head><title>ATLAS Report</title></head><body><h1>ATLAS R17 Report</h1>$html</body></html>" | Out-File $ReportHTML -Encoding utf8
#endregion

Write-Host "PS100-ATLAS Done: $ReportMD" -ForegroundColor Green
Write-Host "PS100-ATLAS Done: $ReportHTML" -ForegroundColor Green