<#
.SYNOPSIS
PS102-Create-Audit-Batches.ps1 - v7.0 LEGACY
.DESCRIPTION
Scans platform\ps-scripts\legacy-ps25\batch-01 to batch-20.
Backs up old audit-batches. Generates 20 batch audit.txt files + PS25-COMBINED-GROUPING-DOC.md + PS25-MANIFEST-MD5.csv
USAGE:.\PS102-Create-Audit-Batches.ps1 -BasePath "C:\Atlas\atlas-workspace"
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$BasePath
)

$ErrorActionPreference = "Stop"

$WorkspaceRoot = $BasePath
$ScriptsRoot = Join-Path $WorkspaceRoot "platform\ps-scripts\legacy-ps25"
$OrchRoot = Join-Path $WorkspaceRoot "orchestration"
$DocsRoot = Join-Path $WorkspaceRoot "docs"
$OutputDir = Join-Path $ScriptsRoot "audit-batches"
$ArchiveRoot = Join-Path $ScriptsRoot "audit-batches-archive"
$DocPath = Join-Path $DocsRoot "PS25-COMBINED-GROUPING-DOC.md"
$ManifestPath = Join-Path $DocsRoot "PS25-MANIFEST-MD5.csv"

Write-Host "=== PS102 v7.0 LEGACY: Creating Audit Batches + Manifest ===" -ForegroundColor Cyan

#region 1. BACKUP EXISTING
$Timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$BackupDir = Join-Path $ArchiveRoot $Timestamp
if (Test-Path $OutputDir) {
    New-Item -ItemType Directory -Path $BackupDir -Force | Out-Null
    Get-ChildItem $OutputDir -File | Move-Item -Destination $BackupDir -Force -ErrorAction SilentlyContinue
    Write-Host "Backed up old audit-batches to $BackupDir" -ForegroundColor Yellow
}
New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
#endregion

#region 2. SCAN BATCHES AND BUILD AUDITS
$BatchFolders = Get-ChildItem $ScriptsRoot -Directory | Where-Object {$_.Name -like "batch-*-*"} | Sort-Object Name
$AllDocs = [System.Collections.ArrayList]@()
$mdTables = [System.Collections.ArrayList]@()

$batchNum = 1
foreach($folder in $BatchFolders){
    $scripts = Get-ChildItem $folder.FullName -Filter "PS*.ps1" | Sort-Object Name
    if($scripts.Count -eq 0){ continue }

    # Create batch audit txt
    $batchFile = Join-Path $OutputDir ("BATCH-{0:D2}-{1}.txt" -f $batchNum, $folder.Name)
    $batchContent = [System.Collections.ArrayList]@()
    $null = $batchContent.Add("BATCH $batchNum : $($folder.Name) | Generated $(Get-Date)")
    $null = $batchContent.Add("=================================================================")
    foreach($s in $scripts){
        $null = $batchContent.Add("=== $($s.Name) ===")
        $null = $batchContent.Add((Get-Content $s.FullName -Raw))
        $null = $batchContent.Add("--- END $($s.Name) ---`n")

        if($s.Name -match '(PS\d+)'){ $psNum = $Matches[1] } else { $psNum = "PS??" }
        $null = $AllDocs.Add([PSCustomObject]@{Batch=$batchNum; Id=$psNum; Name=$s.Name; Path=$s.FullName})
    }
    $batchContent | Out-File $batchFile -Encoding utf8
    Write-Host "Created: $($batchFile | Split-Path -Leaf)" -ForegroundColor Green

    # Build MD table row
    $range = "$($scripts[0].BaseName) to $($scripts[-1].BaseName)"
    $null = $mdTables.Add("| $batchNum | $($folder.Name) | $range |")
    $batchNum++
}
#endregion

#region 3. GENERATE MASTER MD
$docContent = @"
# PS25 Master Script Documentation - Legacy Platform
Generated: $(Get-Date)
Total Scripts: $($AllDocs.Count)
Location: atlas-workspace\docs\PS25-COMBINED-GROUPING-DOC.md

## FOLDER CONVENTION
`orchestration\` = Drivers: PS-MASTER-RUN, PS98, PS99, PS100, PS102
`platform\ps-scripts\legacy-ps25\batch-XX\` = Workers: PS26-PS125
`platform\ps-scripts\legacy-ps25\backend\` = Legacy BE-PS57 to BE-PS80
`platform\ps-scripts\legacy-ps25\frontend\` = Legacy FE-PS48 to FE-PS52

## BATCH MAPPING - PS26-PS125
| Batch | Folder | Scripts |
| --- | --- | --- |
$(($mdTables) -join "`n")

*Generated by PS102-Create-Audit-Batches.ps1 v7.0*
"@

$docContent | Out-File $DocPath -Encoding utf8
Write-Host "Created: $DocPath" -ForegroundColor Green
#endregion

#region 4. GENERATE MD5 MANIFEST
Write-Host "Generating MD5 Manifest..." -ForegroundColor Cyan
$allPs1 = @()
$allPs1 += Get-ChildItem $ScriptsRoot -Recurse -Include *.ps1
$allPs1 += Get-ChildItem $OrchRoot -Filter *.ps1

$manifest = [System.Collections.ArrayList]@()
$null = $manifest.Add("File,RelativePath,Group,Batch,MD5,Purpose,LastModified")

foreach($f in $allPs1 | Sort-Object FullName){
    $md5 = Get-FileHash $f.FullName -Algorithm MD5 | Select-Object -ExpandProperty Hash
    $relPath = $f.FullName.Replace($BasePath, "").TrimStart('\')
    $batch = if($f.Directory.Name -like "batch-*"){$f.Directory.Name} elseif($f.Directory.Name -eq "orchestration"){"orchestration"} else {$f.Directory.Name}
    $group = switch -Wildcard ($batch) {
        "backend" {"BE"} "frontend" {"FE"} "orchestration" {"ROOT"} "batch-*" {"BATCH"} default {"OTHER"}
    }

    # Safe purpose extraction
    $purposeMatch = Select-String -Path $f.FullName -Pattern "# PURPOSE: (.+)" | Select-Object -First 1
    if($purposeMatch -and $purposeMatch.Matches.Count -gt 0){
        $purpose = $purposeMatch.Matches[0].Groups[1].Value.Trim()
    } else {
        $purpose = "PS25 automation task"
    }

    $lastMod = $f.LastWriteTime.ToString("yyyy-MM-dd HH:mm")
    $null = $manifest.Add("$($f.Name),$relPath,$group,$batch,$md5,""$purpose"",$lastMod")
}

$manifest | Out-File $ManifestPath -Encoding utf8
Write-Host "Created: $ManifestPath" -ForegroundColor Green
Write-Host "Total files hashed: $($allPs1.Count)" -ForegroundColor Cyan
#endregion

Write-Host "`nPS102 LEGACY Done. Archive: $ArchiveRoot" -ForegroundColor DarkGray